### ISSUE TITLE
Add a unit test suite

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase-template#19]
#18 fixed a problem with the generated pyproject.toml that was inadvertently introduced when Docker support was added to the template. This fix wouldn't have been needed at all if there was basic pre-merge testing, implemented as a unit test suite.

We should add unit tests template itself. Cookiecutter can be invoked programmatically; so we can run the template with a fixed context and check key properties of the output, like:
* Can `pyproject.toml` be parsed without error? 
* Can `app.py` be compiled without a syntax error? (we don't have to run it - we can use [py_compile](https://docs.python.org/3/library/py_compile.html) to *compile* the code to detect errors)
* Does flake8 raise any errors on the generated code?

This should be a pytest suite, wrapped with a tox configuration. There should also be a Github Actions configuration that invokes the test suite on every PR. The CI configuration for Briefcase will serve as a starting point for this test setup.

**Comment by GenevieveBuckley** [comment]
The Driven Data cookicutter for data science has a reasonably extensive test suite, which I found useful to look at. The repository is at: https://github.com/drivendata/cookiecutter-data-science

**Comment by freakboy3742** [comment]
Fixed by #21.
