### ISSUE TITLE
Using template leads to non working app setup, when using spaces in app name.

### ISSUE THREAD

**Issue by Ocupe** [beeware/briefcase-template#2]
When using a app name that includes spaces, like `Test  App`.
We end up with a non working app because of a syntax error
`from Test App.app import main` in `Test App/__main__.py`

**Comment by cdeil** [comment]
Just now I tried briefcase for the first time and also made a similar mistake.

In the cookiecutter one can use `hello-world` as app name, and then one gets a broken app:
```
from hello-world.app import main
```
Should be possible to add a check that app name has to be a valid Python identifier, no?

**Comment by cdeil** [comment]
Is this the way to do it?
http://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html#example-validating-template-variables

**Comment by huangyun13145461** [comment]
install brew, then install python python3, then install 

If you dont have homebrew installed , enter this command in your terminal
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Next 'brew install awscli'
This will install aws cli on your mac 

$ brew reinstall python python3
$ brew install python3 && cp /usr/local/bin/python3 /usr/local/bin/python
$ npm install pip
$ pip install cookiecutter
$ pip install briefcase
$ cookiecutter https://github.com/pybee/briefcase-template

**Comment by zanebclark** [comment]
I've observed that this is still an issue for Windows 10.
