### ISSUE TITLE
Use "compatible release" syntax in pyproject.toml

### ISSUE THREAD

**Issue by mhsmith** [beeware/briefcase-template#38]
pyproject.toml currently contains requirements like `toga-cocoa>=0.3.0.dev38`. Because this has no upper limit, it's bound to cause a compatibility problem eventually, when we make changes to Toga which aren't compatible with old versions of the templates.

Since Toga is now moving to simple 3-level version numbers with no "dev" suffix (https://github.com/beeware/toga/issues/1670), how about changing the template to use ["compatible release"](https://peps.python.org/pep-0440/#compatible-release) syntax like `toga-cocoa~=0.3.0`? Then, the next time we make a backward incompatible change to Toga, we increment the version number to 0.4.x, and it won't be picked up by any existing project until it's regenerated with a compatible version of the template.

**Comment by freakboy3742** [comment]
+1. The only reason the version specifier is currently `>=` is because of the `.dev` release; as soon as we're formally on the 0.3.0 final, we can clean up these references (as well as removing references to `pip install --pre` in a few documentation sources).
