### ISSUE TITLE
Use `pyside6-essentials` rather than `pyside6` on new apps.

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase-template#73]
### What is the problem or limitation you are having?

When a user specifies that they want to use PySide6 as a GUI framework, Briefcase currently includes `pyside6` as the requirement. 

Qt now provides a `pyside6-essentials` package which is substantially smaller, but provides all the core widgets needed for a simple Qt app. `pyside6-addons` provides other widgets.

### Describe the solution you'd like

When using PySide6, the briefcase template should specify `PySide6-Essentials` rather than `pyside6`, and provide a second (commented out) inclusion of `PySide6-Addons` so that it's easy for users to get the extra widgets if they need them. 

### Describe alternatives you've considered

Continue to use the full PySide6 package.

### Additional context

Once this change lands, it may be possible to re-enable the Windows packaging tests for pyside6 (see  https://github.com/beeware/briefcase-windows-app-template/blob/main/.github/workflows/ci.yml#L36 and https://github.com/beeware/briefcase-windows-VisualStudio-template/blob/main/.github/workflows/ci.yml#L36), as the path issue should no longer exist.

**Comment by NMertsch** [comment]
It looks like the `required` section in pyproject.toml is already updated (def11f90bc54cc55bf81074ab7b255dcd45e819c).

**Comment by freakboy3742** [comment]
Yes - this was fixed yesterday in #74.
