### ISSUE TITLE
Veralgemeinern

### ISSUE THREAD

**Issue by NADOOITChristophBa** [beeware/briefcase-template#96]
```
#TODO Veralgemeinern
```

https://github.com/NADOOIT/batteries-included-briefcase-template/blob/dc140754ae57ed576b223045cff36cd667611b17/%7B%7B%20cookiecutter.app_name%20%7D%7D/src/%7B%7B%20cookiecutter.module_name%20%7D%7D/services.py#L95

**Comment by mhsmith** [comment]
I assume you created this issue by accident. If you need help, please post another comment below.

**Comment by NADOOITChristophBa** [comment]
Sorry this was supposed to be created in my fork and I guess git just put it in the origin
